/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VocabularyIndexRouteImport } from './routes/vocabulary.index'
import { Route as VocabularyWordIdRouteImport } from './routes/vocabulary.$wordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyIndexRoute = VocabularyIndexRouteImport.update({
  id: '/vocabulary/',
  path: '/vocabulary/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyWordIdRoute = VocabularyWordIdRouteImport.update({
  id: '/vocabulary/$wordId',
  path: '/vocabulary/$wordId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vocabulary/$wordId': typeof VocabularyWordIdRoute
  '/vocabulary/': typeof VocabularyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vocabulary/$wordId': typeof VocabularyWordIdRoute
  '/vocabulary': typeof VocabularyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vocabulary/$wordId': typeof VocabularyWordIdRoute
  '/vocabulary/': typeof VocabularyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vocabulary/$wordId' | '/vocabulary/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vocabulary/$wordId' | '/vocabulary'
  id: '__root__' | '/' | '/vocabulary/$wordId' | '/vocabulary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VocabularyWordIdRoute: typeof VocabularyWordIdRoute
  VocabularyIndexRoute: typeof VocabularyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/': {
      id: '/vocabulary/'
      path: '/vocabulary'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof VocabularyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/$wordId': {
      id: '/vocabulary/$wordId'
      path: '/vocabulary/$wordId'
      fullPath: '/vocabulary/$wordId'
      preLoaderRoute: typeof VocabularyWordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VocabularyWordIdRoute: VocabularyWordIdRoute,
  VocabularyIndexRoute: VocabularyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
